baseURL = 'https://wangdong.github.io/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
title = '朔方札记'
theme = 'PaperMod'
copyright = "© 2024 王冬 · 保留所有权利"

# 时间和日期格式
timeFormat = "2006年1月2日 15:04:05"
dateFormat = "2006年1月2日"

[params]
  author = "王冬"
  description = "思考与记录"
  keywords = ["blog", "思考", "记录"]
  showReadingTime = false
  showShareButtons = false
  showPostNavLinks = false
  showBreadCrumbs = false
  showCodeCopyButtons = true
  showToc = false
  defaultTheme = "auto"
  DateFormat = "2006年1月2日"

[params.homeInfoParams]
  Title = "朔方札记 ✍️"
  Content = "思考与记录"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/wangdong"

[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/wangdong"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/wangdong027/"


[menu]
  [[menu.main]]
    identifier = "posts"
    name = "目录"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "books"
    name = "书单"
    url = "/books/"
    weight = 20


[outputs]
  home = ["HTML", "RSS", "JSON"]
