baseURL = 'https://wangdong.github.io/'
languageCode = 'zh-cn'
title = '朔方札记'
theme = 'PaperMod'
copyright = "© 2024 王冬 · 保留所有权利"

[params]
  author = "王冬"
  description = "思考与记录"
  keywords = ["blog", "思考", "记录"]
  showReadingTime = false
  showShareButtons = false
  showPostNavLinks = false
  showBreadCrumbs = false
  showCodeCopyButtons = true
  showToc = false
  defaultTheme = "auto"

[params.homeInfoParams]
  Title = "朔方札记 ✍️"
  Content = "思考与记录"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/wangdong"

[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/wangdong"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/wangdong027/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
